#TABLE

19

"beat"
8
1
1
1
"You @rbeat@n your chest like a @grampaging gorilla!"
"$n @rbeats@n $s chest @ysquealing@n with a @rmighty fury!"
"You commence @rBeating@n $N about the head and shoulders."
"@yMadly squealing,@n $n begins @rbeating@n $N about the head and shoulders."
"With an @yinsane squeal,@n $n begins to @rBeat@n you about the head and shoulders."
"You have dream of a severe beating about the head and shoulders."
""
""
"You @rbeat@n $p angrily."
"$n @rbeats@n $p angrily."
""
""
"You threaten to @rbeat@n $N with $p."
"$n threatens to @rbeat@n you with $p."
"$n threatens to @rbeat@n $N with $p."
""
""
""
""

"bscratch"
0
0
0
0
"Scratching a painful itch, a fine cloud of dust erupts from your hairy back."
"$n squeals as $e tries to scratch $s back.  A fine cloud of dust erupts from $s hairy back."
"Out of the kindness of your heart, you scratch $N's back."
"$n kindly scratches $Ns back.  Jealous?"
"$n scratches your back.   Aaahhhhh... doesnt that feel good?"
""
""
""
""
""
""
""
""
""
""
""
""
""
""

"cry"
0
0
0
0
"You cry softly, sniffling through your wet snout."
"$n cries softly, sniffling through $s wet snout."
"You cry on $s shoulder, sniffling through your wet snout."
"$n cries on $N's shoulder, sniffling and leaving a @gsnotty mess.@n"
"$n cries on your shoulder, sniffling loudly in your ear."
""
""
""
""
""
"Looking $t you can't help but cry."
"$n looks $t and begins to cry.  Big orcish tears covering $s cheeks."
""
""
""
""
""
""
""

"ear"
0
0
0
0
""
""
"Pushing a fat finger deeply into $N's ear, you search for lost treasure."
"$n buries a fat finger deeply in $N's ear.  $n smiles at the wonderful wax $e finds."
"You feel a fat finger penetrate your ear.  $n smiles at the large amount of wax $e finds."
"Your dreams are disturbed by the presence of a fat finger probing your ear."
"With high hopes, you push a fat finger deep into your ear.  Who knows what may be hidden there?"
"Pushing a fat finger deep into $s ear, $n roots around for lost treasure."
""
""
""
""
""
""
""
""
""
""
""

"grin"
6
0
0
0
"Grinning evilly, you flash your tusks."
"Flashing $s tusks, $n grins evilly."
"Flashing your tusks, you grin evilly at $N."
"$n grins evilly at $N, flashing his tusks."
"Grinning evilly at you, $n's tusks become very apparent."
""
""
""
""
""
""
""
""
""
""
""
""
""
""

"grunt"
6
0
0
0
"You grunt like a pig."
"$n grunts like a pig."
"You grunt like a pig at $N."
"$n grunts like a pig at $N."
"$n grunts like a pig at you."
""
"You grunt happily to yourself."
"$n grunts happily to $mself."
""
""
""
""
""
""
""
""
""
""
""

"jump"
8
0
1
1
"You jump up and down, both fat feet slapping the ground."
"$n's fat feet slap the ground as $e jumps up and down."
"You jump up and down on $N feeling $S insides @gsquish@n about."
"$n jumps up and down on $N, @gsquishing@n $S insides all about."
"$n jumps up and down on you, @gsquishing@n your insides all about."
"Someone jumps up and down on you, your insides will never be the same."
""
""
""
""
""
""
""
""
""
""
""
""
""

"laugh"
6
0
1
0
"You laugh and snort, @gichor@n dripping from your tusks."
"$n laughs and snorts, @gichor@n dripping from $s tusks."
"You laugh and snort at $N, @gichor@n dripping from your tusks."
"$n laughs and snorts at $N, @gichor@n dripping from $s tusks."
"$n laughs and snorts at you, @gichor@n dripping from $s tusks."
""
"You laugh and snort at yourself, @gichor@n dripping from your tusks."
"$n laughs and snorts at $mself, @gichor@n dripping from $s tusks."
"You laugh and snort at $p, @gichor@n dripping from your tusks."
"$n laughs and snorts at $p, @gichor@n dripping from $s tusks."
"You make a lot of snorting noises as you look $t and laugh."
"$n makes a lot of snorting noises as $e looks $t and laughs."
"You look at $N and laugh, snorting excitedly as you hold $p in the air."
"$n looks at you and laughs, snorting excitedly as $e holds $p in the air."
"$n looks at $N and laughs, snorting excitedly as $e holds $p in the air."
""
"You laugh and snort at yourself, wiping @gichor@n from your tusks onto $p."
"$n laughs and snorts at $mself, wiping @gichor@n from $s tusks onto $p."
""

"lick"
0
0
0
0
""
""
"You lick $N with your @mcoarse, wet tongue@n, absentmindedly jabbing with your tusks."
"$n gives $N a @mlong, wet lick@n."
"Absentmindedly poking you with $s tusks, $n gives you a @mlong, wet lick@n."
"You feel a @mlong, wet lick@n, followed by the dull jab of tusks."
"You lick your tusks, @gdrooling@n in anticipation."
"$n licks $s tusks, @gdrooling@n in anticipation."
""
""
""
""
""
""
""
""
""
""
""

"nod"
6
0
0
0
"You nod, sending @gdrool@n sliding down your tusks."
"$n nods, sending @gdrool@n sliding down $s tusks."
"You nod your tusked head at $N, shaking @gdrool@n at $M."
"$n nods $s tusked head at $N, shaking @gdrool@n at $M."
"$n nods $s tusked head, shaking @gdrool@n at you."
"You feel something @gwet@n splatter your face."
"You nod your tusked head vigorously, shaking @gdrool@n everywhere."
"$n nods $s tusked head vigorously, shaking @gdrool@n everywhere."
"You nod your tusked head, shaking @gdrool@n onto $p."
"$n nods $s tusked head, shaking @gdrool@n onto $p."
"You nod $t, sending @gdrool@n sliding down your tusks."
"$n nods $t, sending @gdrool@n sliding down $s tusks."
"You nod your tusked head at $p, shaking @gdrool@n onto $N."
"$n nods $s tusked head at $p, shaking @gdrool@n onto you."
"$n nods $s tusked head at $p, shaking @gdrool@n onto $N."
"You feel something @gwet@n splatter your face."
"You nod your tusked head vigorously at $p, drenching yourself in @gdrool@n."
"$n nods $s tusked head vigorously at $p, drenching $mself in @gdrool@n."
""

"nose"
6
0
0
0
"You pick your nose, buried in deep thought."
"$n picks his nose, buried in deep thought."
"You pick your nose, wiping what you found on $N."
"$n picks his nose and wipes his finger on $N."
"$n picks his nose, and wipes the content of his slimy finger on your armor."
""
"You pick your nose and wipe it on your armor."
"$n picks his nose and wipes it all over his clothes."
""
""
""
""
""
""
""
""
""
""
""

"smile"
6
0
0
0
"You smile happily, showing off your fine set of tusks."
"$n smiles happily, showing off $s fine set of tusks."
"Beaming a smile at $N, you flaunt your fine set of tusks."
"$n beams a smile at $N, $s fine orcish tusks gleaming."
"$n smiles happily at you, showing off $s fine set of tusks."
""
""
""
""
""
""
""
""
""
""
""
""
""
""

"snarl"
6
0
0
0
"Your gnash your tusks and snarl."
"$n gnashes his tusks as $e snarls."
"You snarl at $N, flashing your tusks."
"$n snarls angrily at $N, flashing $s tusks."
"$n snarls angrily at you, flashing $s tusks."
""
"You snarl at yourself."
"$n snarls at $mself."
""
""
""
""
""
""
""
""
""
""
""

"sniff"
6
0
0
1
"You poke your snout around, sniffing and snorting."
"$n pokes $s snout around, sniffing and snorting."
"You sniff and snort at $N, poking $M with your tusks and snout."
"$n sniffs and snorts at $N, poking $M with $s tusks and snout."
"$n sniffs and snorts at you, poking you with $s tusks and snout."
"Something wet and @gslimy@n sniffles across your face, poking you with a tusk."
"You rubs your snout all over your body, sniffing and snorting."
"$n rubs $s snout all over $s body, sniffing and snorting."
"You sniff and snort, poking $p with your tusks."
"$n sniffs and snorts, poking $p with $s tusks."
"Your nostrils flare and your snout scrunches as you sniff $t."
"$n's nostrils flare and $s snout scrunches as $e sniffs $t."
"You stuff $p into your snout and sniff at $N, poking $M with your tusks."
"$n stuffs $p into $s snout and sniffs at you, poking you with $s tusks."
"$n stuffs $p into $s snout and sniffs at $N, poking $M with $s tusks."
"Something wet and @gslimy@n sniffles across your face, poking you with a tusk."
"You stuff $p into your snout and sniff your body, poking yourself with your tusks."
"$n stuffs $p into $s snout and sniffs $s body, poking $mself with $s tusks."
""

"snort"
0
0
0
0
"Your snout curls as you snort loudly."
"$n's snout curls as $e snorts loudly."
"You snort angrily at $N."
"$n snorts angrily at $N."
"$n snorts angrily at you."
""
"You absentmindedly snort to yourself."
"$n absentmindedly snorts to $mself."
""
""
""
""
""
""
""
""
""
""
""

"stomp"
8
0
1
1
"@CStomping@n one foot down, then the other, you begin a famed orcish dance."
"@CStomping@n one foot down, then the other, $n begins a famed orcish dance."
"You grab $N's hands and try to teach $M an orcish @cStomp@n.  It's not your fault $E has two left feet."
"Grabbing $N's hands, $n attempts to teach $M a famed orcish @cStomp@n.  $N winces as $n @cStomps@n upon $S feet."
"Grabbing your hands, $n attempts to teach you a famed orcish @cStomp@n.  Unfortunately, your feet get in the way. @rOUCH!@n"
""
""
""
"Using both feet, you @CSTOMP@n repeatedly on $p!"
"Using both feet, $n @CSTOMPS@n repeatedly on $p!"
""
""
""
""
""
""
""
""
""

"think"
6
0
0
0
"You slowly stroke your tusks, deep in thought."
"In deep thought, $n slowly strokes $s tusks."
"Slowly stroking your tusks, you think of $N's many problems."
"Slowly stroking $s tusks, $n thinks of $N's many problems."
"Slowly stroking his tusks, $n thinks of all your many problems."
""
""
""
""
""
""
""
""
""
""
""
""
""
""

"wrinkle"
6
0
0
0
"Showing your disgust, you wrinkle your snout."
"Showing $s disgust, $n wrinkles his snout."
"With great disgust, you wrinkle your snout at $N."
"Showing great disgust, $n wrinkles $s snout at $N."
"Wrinkling $s snout, $n is disgusted with you."
""
""
""
""
""
""
""
""
""
""
""
""
""
""

"yawn"
6
0
0
0
"You let out a big yawn."
"$n lets out a big yawn."
"You yawn at $N."
"$n yawns at $N."
"$n yawns at you."
""
"You let out a big yawn."
"$n lets out a big yawn."
""
""
""
""
""
""
""
""
""
""
""


